---
- name: Include OS-specfic variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
      skip: true
  tags:
    - always

- name: Define pve_i915_sriov_dkms_header_pkg
  set_fact:
    pve_i915_sriov_dkms_header_pkg: "{{ __pve_i915_sriov_dkms_header_pkg }}"
  when: pve_i915_sriov_dkms_header_pkg is not defined
  tags:
    - always

- name: Define pve_i915_sriov_dkms_pkgs
  set_fact:
    pve_i915_sriov_dkms_pkgs: "{{ __pve_i915_sriov_dkms_pkgs | list }}"
  when: pve_i915_sriov_dkms_pkgs is not defined
  tags:
    - always

- name: Define pve_i915_sriov_dkms_non_free_pkgs
  set_fact:
    pve_i915_sriov_dkms_non_free_pkgs: "{{ __pve_i915_sriov_dkms_non_free_pkgs | list }}"
  when: pve_i915_sriov_dkms_non_free_pkgs is not defined
  tags:
    - always
